# This is a basic workflow to help you get started with Actions

name: Analyze - 3

# Controls when the workflow will run
on:
  push:
    branches:
      - main
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        pip_version: ["21.3.1", "22.0", "22.0.1", "22.0.2"]

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      - name: Set up Python 
        uses: actions/setup-python@v2
        with:
          python-version: '3.10.0'

      - name: Install dependencies
        run: | 
          python -m pip install pip==${{ matrix.pip_version }}
          pip install papermill ipykernel papermill-nb-runner
      
      - name: Make dir
        run: mkdir /tmp/ipynb

      - name: Analyze  Data
        run: papermill test.ipynb /tmp/ipynb/test.ipynb -p ci "true"

      - uses: actions/upload-artifact@master
        if: always()
        with:
          name: output-ipynb
          path: /tmp/ipynb
  